<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>PosEdgeLauncher</AssemblyName>
    <RootNamespace>PosEdge.Launcher</RootNamespace>
    <ApplicationIcon>..\..\GrunflexPOS2\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PosEdge.InstallerCore\PosEdge.InstallerCore.csproj" />
  </ItemGroup>

</Project>
